"""
Data loading and normalization layer.

Every analysis module downstream (metrics, comparisons, investigation, ...)
works against pandas DataFrames with known column names and dtypes -- it
never touches a raw CSV or a platform-specific schema directly. That
separation is what lets a future real connector (Google Ads API, GA4, Meta,
...) plug in later: as long as it produces a DataFrame with these same
columns, nothing in the analysis layer has to change.

For now, all data comes from synthetic CSVs generated by
scripts/generate_synthetic_data.py (see data/ and README.md).
"""

import os
import pandas as pd

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")


class DataNotFoundError(Exception):
    """Raised when a required data file is missing or empty."""


def _read_csv(filename, date_columns=None, required_columns=None):
    path = os.path.join(DATA_DIR, filename)
    if not os.path.exists(path):
        raise DataNotFoundError(
            f"Expected data file not found: {path}\n"
            f"Run `python3 scripts/generate_synthetic_data.py` to generate the synthetic dataset."
        )
    df = pd.read_csv(path)
    if df.empty:
        raise DataNotFoundError(f"{path} exists but contains no rows.")
    if required_columns:
        missing = set(required_columns) - set(df.columns)
        if missing:
            raise DataNotFoundError(f"{path} is missing expected columns: {sorted(missing)}")
    if date_columns:
        for col in date_columns:
            df[col] = pd.to_datetime(df[col]).dt.date
    return df


def load_campaigns():
    return _read_csv(
        "campaigns.csv",
        date_columns=["date"],
        required_columns=[
            "date", "platform", "channel", "campaign", "campaign_type",
            "impressions", "clicks", "spend", "conversions", "conversion_value",
            "monthly_budget",
        ],
    )


def load_keywords():
    return _read_csv(
        "keywords.csv",
        date_columns=["date"],
        required_columns=[
            "date", "platform", "campaign", "keyword", "match_type",
            "impressions", "clicks", "spend", "conversions", "conversion_value",
        ],
    )


def load_search_terms():
    return _read_csv(
        "search_terms.csv",
        date_columns=["date"],
        required_columns=[
            "date", "platform", "campaign", "search_term", "matched_keyword",
            "impressions", "clicks", "spend", "conversions", "conversion_value",
        ],
    )


def load_changes():
    return _read_csv(
        "changes.csv",
        date_columns=["date"],
        required_columns=[
            "date", "platform", "campaign", "entity", "change_type",
            "old_value", "new_value", "changed_by", "notes",
        ],
    )


def load_auction_insights():
    return _read_csv(
        "auction_insights.csv",
        date_columns=["week_start_date"],
        required_columns=[
            "week_start_date", "platform", "campaign", "impression_share",
            "outranking_share", "lost_is_rank", "lost_is_budget", "top_competitor",
        ],
    )


def load_scenario_ground_truth():
    return _read_csv(
        "scenario_ground_truth.csv",
        required_columns=["scenario_id", "campaign", "start_date", "end_date", "expected_primary_driver"],
    )


def load_all():
    """Convenience loader used by the Streamlit app to fetch every dataset once."""
    return {
        "campaigns": load_campaigns(),
        "keywords": load_keywords(),
        "search_terms": load_search_terms(),
        "changes": load_changes(),
        "auction_insights": load_auction_insights(),
        "scenario_ground_truth": load_scenario_ground_truth(),
    }
